// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef PathFinder_h
#define PathFinder_h
#include <FL/Fl.H>
#include "pathfinder_t.h"
#include <FL/fl_ask.H>
#include <stdio.h>
#include <stdlib.h>
#include "Cell.h"
extern map_t map;
extern short *cells;
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Counter.H>
extern Fl_Counter *X_limit;
extern Fl_Counter *Y_limit;
#include <FL/Fl_Button.H>
#include <FL/Fl_Scroll.H>
extern Fl_Scroll *Map;
Fl_Double_Window* make_window();
#endif
