// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef Edge_h
#define Edge_h
#include <FL/Fl.H>
#include <FL/Fl_File_Chooser.H>
#include "Fl_OpenCV.H"
extern IplImage *cedge, *gray , *edge,*temp;
extern Fl_OpenCV *Pict;
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
extern void Open_CB(Fl_Button*, void*);
extern Fl_Button *Open;
#include <FL/Fl_Value_Slider.H>
extern void Edge_CB(Fl_Value_Slider*, void*);
extern Fl_Value_Slider *Edge;
extern void Save_CB(Fl_Button*, void*);
extern Fl_Button *Save;
#include <FL/Fl_Scroll.H>
extern Fl_Scroll *Board;
#include <FL/Fl_Browser.H>
extern Fl_Browser *Data;
Fl_Double_Window* make_window();
void Open_CB(Fl_Widget*,void*);
void Save_CB(Fl_Widget*,void*);
void Edge_CB(Fl_Widget*,void*);
#endif
