// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef Nodul_h
#define Nodul_h
#include <FL/Fl.H>
#include <FL/Fl_File_Chooser.H>
#include "Fl_OpenCV.H"
#include <fann.h>
extern IplImage *numune;
extern uchar lut[256];
extern CvMat* lut_mat;
extern Fl_OpenCV *Pict;
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
extern void Open_CB(Fl_Button*, void*);
extern Fl_Button *Open;
#include <FL/Fl_Scroll.H>
extern Fl_Scroll *Board;
#include <FL/Fl_Browser.H>
extern Fl_Browser *Data;
#include <FL/Fl_Output.H>
extern Fl_Output *FName;
extern Fl_Button *Bul;
Fl_Double_Window* make_window();
void Open_CB(Fl_Widget*,void*);
void GetIdentty(IplImage *image, fann_type *ID);
void FindNodule();
#endif
