// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef EyeFind_h
#define EyeFind_h
#include <FL/Fl.H>
#include <FL/Fl_File_Chooser.H>
#include "Fl_OpenCV.h"
#include "EyeFinder.h"
#include <fann.h>
extern IplImage *img;
extern Fl_Capture Cap;
extern CvMemStorage* storage;
extern CvHaarClassifierCascade* cascade;
extern Fl_OpenCV *Pict;
bool playing;
extern EyeFinder *Eyes;
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *Win;
#include <FL/Fl_Button.H>
extern Fl_Button *Open;
#include <FL/Fl_Scroll.H>
extern Fl_Scroll *Board;
#include <FL/Fl_Output.H>
extern Fl_Output *FName;
extern Fl_Button *Bul;
#include <FL/Fl_Choice.H>
extern Fl_Choice *Source;
extern Fl_Button *Save;
Fl_Double_Window* make_window();
void Open_CB();
void OpenVideo_CB();
void FindFaces();
int detect_and_draw();
void LoadHaarClassifier();
void Video_FindFaces();
void Playing_CB(void*);
#include <FL/Fl_Return_Button.H>
extern void cb_Ok(Fl_Return_Button*, void*);
#include <FL/Fl_Browser.H>

class AboutDlg {
public:
  AboutDlg();
  Fl_Double_Window *window;
  Fl_Return_Button *Ok;
  Fl_Browser *Info;
  void show();
  void hide();
};
void cb_Ok(Fl_Return_Button*o, void*w);
#endif
