// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef main_h
#define main_h
#include <FL/Fl.H>
#include <FL/fl_ask.H>
#include <fann.h>
#include <stdio.h>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *window_main;
#include <FL/Fl_Input.H>
extern Fl_Input *Age;
#include <FL/Fl_Button.H>
#include <FL/Fl_Output.H>
extern Fl_Output *To;
#include <FL/Fl_Choice.H>
extern Fl_Choice *Sex;
extern Fl_Choice *Chest;
extern Fl_Input *BPress;
extern Fl_Input *Cholestral;
extern Fl_Choice *Ecg;
extern Fl_Input *HRate;
extern Fl_Choice *Exc;
extern Fl_Input *Oldpeak;
extern Fl_Choice *Slope;
extern Fl_Choice *NVessel;
extern Fl_Choice *Thal;
extern Fl_Choice *BSugar;
void Hesapla();
#endif
