// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef Face_h
#define Face_h
#include <FL/Fl.H>
#include <FL/Fl_File_Chooser.H>
#include "Fl_OpenCV.H"
#include <fann.h>
extern IplImage *img; 
extern Fl_Capture Cap; 
extern CvMemStorage* storage; 
extern CvHaarClassifierCascade* cascade; 
extern Fl_OpenCV *Pict; 
bool playing; 
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *Win;
#include <FL/Fl_Button.H>
extern Fl_Button *Open;
#include <FL/Fl_Scroll.H>
extern Fl_Scroll *Board;
#include <FL/Fl_Output.H>
extern Fl_Output *FName;
extern Fl_Button *Bul;
#include <FL/Fl_Choice.H>
extern Fl_Choice *Type;
extern Fl_Choice *Source;
Fl_Double_Window* make_window();
void Open_CB();
void OpenVideo_CB();
void FindFaces();
int detect_and_draw();
void LoadHaarClassifier();
void LoadTypes();
void Video_FindFaces();
void Playing_CB(void*);
#endif
