// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef main_h
#define main_h
#include <FL/Fl.H>
#include "Fl_PlotXY.H"
#include <FL/Fl_Double_Window.H>
extern Fl_PlotXY *plot;
#include <FL/Fl_Button.H>
extern Fl_Button *start;
#include <FL/Fl_Browser.H>
extern Fl_Browser *out;
#include <FL/Fl_Value_Output.H>
extern Fl_Value_Output *PRota;
#include <FL/Fl_Dial.H>
extern Fl_Dial *Dm;
#include <FL/Fl_Box.H>
extern Fl_Value_Output *PPos;
extern Fl_Value_Output *PAngle;
void SimulationStart();
double Rota(double t);
void Simulate(void *);
double GetNewY(double y,double ry,double ryn );
#endif
