// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef Treshold_h
#define Treshold_h
#include <FL/Fl.H>
#include <FL/Fl_File_Chooser.H>
#include "Fl_OpenCV.H"
#include <fann.h>
extern IplImage *src;
extern IplImage *trsh;
extern Fl_OpenCV *Pict;
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *Win;
#include <FL/Fl_Button.H>
extern void Open_CB(Fl_Button*, void*);
extern Fl_Button *Open;
#include <FL/Fl_Scroll.H>
extern Fl_Scroll *Board;
#include <FL/Fl_Output.H>
extern Fl_Output *FName;
#include <FL/Fl_Value_Slider.H>
extern Fl_Value_Slider *Thresh;
#include <FL/Fl_Choice.H>
extern Fl_Choice *Type;
extern Fl_Value_Slider *Max;
extern void Save_CB(Fl_Button*, void*);
extern Fl_Button *Save;
Fl_Double_Window* make_window();
void Open_CB(Fl_Widget*,void*);
void LoadTypes();
void Apply();
void Close(Fl_Window*,void*);
void Save_CB(Fl_Widget*,void*);
#endif
