// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef FaceRec_h
#define FaceRec_h
#include <FL/Fl.H>
#include <FL/Fl_File_Chooser.H>
#include "Fl_OpenCV.h"
#include "cvaux.h"
#include <vector>
#include <string>
using namespace std;
extern vector <string> names; 
extern vector <string> files; 
IplImage ** faceImgArr        = 0; // array of face images
CvMat    *  personNumTruthMat = 0; // array of person numbers
int nTrainFaces               = 0; // the number of training images
int nEigens                   = 0; // the number of eigenvalues
IplImage * pAvgTrainImg       = 0; // the average image
IplImage ** eigenVectArr      = 0; // eigenvectors
CvMat * eigenValMat           = 0; // eigenvalues
CvMat * projectedTrainFaceMat = 0; // projected training faces
extern IplImage *img,*yuzg; 
extern Fl_Capture Cap; 
extern CvMemStorage* storage; 
extern CvSeq* faces; 
extern CvHaarClassifierCascade* cascade; 
extern Fl_OpenCV *Pict; 
extern Fl_OpenCV *fFace; 
extern bool playing,extracting; 
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *Win;
#include <FL/Fl_Scroll.H>
extern Fl_Scroll *Board;
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
extern Fl_Input *Name;
#include <FL/Fl_Button.H>
extern Fl_Button *Open;
extern Fl_Button *ExtractBut;
extern Fl_Button *SaveBut;
extern Fl_Button *Learn;
extern Fl_Button *Recognize;
#include <FL/Fl_Browser.H>
extern Fl_Browser *List;
extern Fl_Browser *Out;
Fl_Double_Window* make_window();
void OpenCAM_CB();
void LoadHaarClassifier();
void Playing_CB(void*);
void Extracting_CB(void*);
bool ExtractFace();
void learn();
void recognize();
void doPCA();
void storeTrainingData();
int loadTrainingData(CvMat ** pTrainPersonNumMat);
int findNearestNeighbor(float * projectedTestFace);
int loadFaceImgArray(char * filename);
void Save_Add();
int LoadTrainData();
void SaveTrainData();
void LoadList();
void SaveList();
#include <FL/Fl_Return_Button.H>
extern void cb_Ok(Fl_Return_Button*, void*);

class AboutDlg {
public:
  AboutDlg();
  Fl_Double_Window *window;
  Fl_Return_Button *Ok;
  Fl_Browser *Info;
  void show();
  void hide();
};
void cb_Ok(Fl_Return_Button*o, void*w);
#endif
