// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef oxo_game_h
#define oxo_game_h
#include <FL/Fl.H>
#include <FL/Fl_Button.H>
#include <FL/fl_ask.H>
#include <stdlib.h>
#include <string.h>
#include "fann.h"
extern struct fann *ann; 
extern struct fann *val; 
extern struct fann *hml; 
extern Fl_Button *But[9]; 
extern float Board[9]; 
extern int count; 
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
extern Fl_Group *Table;
#include <FL/Fl_Button.H>
extern void cb_But(Fl_Button*, void*);
extern Fl_Button *But0;
extern Fl_Button *But1;
extern Fl_Button *But2;
extern Fl_Button *But3;
extern Fl_Button *But4;
extern Fl_Button *But5;
extern Fl_Button *But6;
extern Fl_Button *But7;
extern Fl_Button *But8;
extern Fl_Group *Method;
#include <FL/Fl_Round_Button.H>
extern Fl_Round_Button *Method1;
#include <FL/Fl_Value_Output.H>
extern Fl_Value_Output *ins;
extern Fl_Value_Output *ysa;
Fl_Double_Window* make_window();
void ComputerMove();
void ComputerMove2();
void InitMove();
void PrintBoard(float *out);
int isEnd(float *brd);
void cb_But(Fl_Button*b, void*u);
void HumanWin();
void ComputerWin();
void EndGame();
void Isaretle(int i,bool isysa);
#endif
